### ISSUE TITLE
Regression in 0.8.0

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-api-client#14]
Unzip and put the attached `bug.py` from [bug.py.zip](https://app.zenhub.com/files/258831302/d823c82a-aed1-4c62-b53e-d35d978cc480/download) into `/tmp` and prepare a virtualenv as follows:
```console
$ python3 -m venv regression
$ cd regression
$ bin/pip install --upgrade --quiet pip
$ bin/pip install pds.api-client==0.7.1
$ bin/python /tmp/bug.py
```
This should work correctly and produce a list of URLs.

Now change the version of `pds.api-client`:
```console
$ bin/pip install pds.api-client==0.8.0
$ bin/python /tmp/bug.py
```
This instead gives a stack trace:
```
Traceback (most recent call last):
  File "/tmp/bug.py", line 23, in <module>
    main()
  File "/tmp/bug.py", line 18, in main
    for url in urls:
  File "/private/tmp/regression/lib/python3.9/site-packages/pds/api_client/model_utils.py", line 443, in __getitem__
    raise ApiAttributeError(
pds.api_client.exceptions.ApiAttributeError: PropertyArrayValues has no attribute '0' at ['['received_data', 'data', 0, 'properties', 'ops:Data_File_Info.ops:file_ref']']
```
Not sure what's going on here! HELP! 😮

**Comment by tloubrieu-jpl** [comment]
@nutjob4life I was too quick, let me check...

**Comment by tloubrieu-jpl** [comment]
@nutjob4life  This is weird... See 
`collection.properties['ops:Data_File_Info.ops:file_ref']
['https://pds-gamma.jpl.nasa.gov/data/pds4/test-data/registry/urn-nasa-pds-insight_documents/document_hp3rad/collection_document_hp3rad.csv']
collection.properties['ops:Data_File_Info.ops:file_ref'][0]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/loubrieu/PycharmProjects/pds-api-client/pds/api_client/model_utils.py", line 446, in __getitem__
    [e for e in [self._path_to_item, name] if e]
pds.api_client.exceptions.ApiAttributeError: PropertyArrayValues has no attribute '0' at ['['received_data', 'data', 0, 'properties', 'ops:Data_File_Info.ops:file_ref']']
`

**Comment by tloubrieu-jpl** [comment]
@nutjob4life since I don't see a change in the specification in that related area, I checked on version 0.7.1 and 0.6.0 (`pip install pds.api-client=={version}`). I reproduced the same behavior as in 0.8.0. Can you check again ?

I was suspecting that the generator we use (either python-legacy before and python now) might cause this regression but since I don't reproduce the behavior you are expected in any of the version I tested, I am not sure...

**Comment by nutjob4life** [comment]
Here's another weird regression:
```python
from pds.api_client import BundlesApi, BundlesCollectionsApi, CollectionsProductsApi
```
This works in 0.4.0, 0.5.0, 0.6.0, 0.6.1, and 0.7.1.

But not in 0.8.0; here, I have to do:
```python
from pds.api_client.api.bundles_api import BundlesApi
from pds.api_client.api.bundles_collections_api import BundlesCollectionsApi
from pds.api_client.api.collections_products_api import CollectionsProductsApi
```
I've also had to change the `Product` import class seemingly every other release. Sometimes it's from `pds.api_client.models.product` (plural `models`), sometimes it's `pds.api_client.model.product` (singular `model`) 🤷‍♀️

This API certainly keeps you on your toes! 😊

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this has been open for 2 months. is there a resolution here? is it something we need to fix or is it something we can just table to some later time?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can we take a look at this ASAP and determine if it is still a regression and/or if it is a known/understood regression?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl checking in here again, do we know if this is still a regression? expected? or not expected? is this a blocker to I&T?

**Comment by jordanpadams** [comment]
issue is with the openapi-generator, plan to investigate different options you can supply when executing openapi-generator.

per the issue noted above, the regression was handled in pds-deep-archive, but this is a future improvement we should look into to ensure backwards compatibility.

**Comment by tloubrieu-jpl** [comment]
For build 12.1 and version 1.0.0 we decide to use the forked openapi generator to create an API client easier to use.

@tloubrieu-jpl will update the documentation subsequently, see https://nasa-pds.github.io/pds-api-client/developer/index.html

**Comment by gxtchen** [comment]
@tloubrieu-jpl @viviant100 The python script is trying to connect to https://pds-gamma.jpl.nasa.gov/api/ which is not available, if I am using the docker image running on my localhost:8080 then what is the host string to the api?

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , which puthon script are you referring to ?

For this script, https://github.com/NASA-PDS/pds-api-client/blob/e17add7db14039bd288126a215f7f531117698e7/client-demo.py#L10

The host can be either:
- http://localhost:8080/ for a local deployement of the registry API
- the equivalent path in production is https://pds.nasa.gov/api/search/1.0/

The pds-gamma path is not maintained anymore.

Let me know which script/documentation is using pds-gamma. We should update that.

thanks,

Thomas

**Comment by tloubrieu-jpl** [comment]
**Currently:**
https://pds.nasa.gov/api --> unavailable
https://pds.nasa.gov/api/search --> unavailable
https://pds.nasa.gov/api/search/1.0 --> pds home page

**Proposal:**
https://pds.nasa.gov/api --> https://nasa-pds.github.io/pds-api/ , create specific page which lists all the deployments
https://pds.nasa.gov/api/search/ --> https://nasa-pds.github.io/pds-api/search  , create specific page which lists all the available versions for this service
https://pds.nasa.gov/api/doi/ --> migrate redirection to cloud-front + create page.
https://pds.nasa.gov/api/search/1.0 --> redoc page

**Future**
Create a different tickets for the rebranding of the swagger pages in registry and doi.
Create a ticket for migrating redirection of DOI API to cloud-front (after everything works on Apache)

References:
look at what CMR does ?

**Comment by tloubrieu-jpl** [comment]
I don't know why these comments landed here, I will create a specific ticket for that
